---
title: "guerin-steven-ADA-homework4"
author: "Steven"
date: "5/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pre-Challenge 

```{r}
library(tidyverse)
library(patchwork) # for plotting
library(scales) # for log y axis scale
library(collapse) # for `fmode()` to find mode
library(BBmisc) # for %nin%
library(devtools)
remotes::install_github("joachim-gassen/tidycovid19")
library(tidycovid19)

merged <- download_merged_data(cached = TRUE)
merged <- merged %>%
  group_by(country, iso3c) %>%
  arrange(country, iso3c, date) %>%
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world1 <- merged %>%
  group_by(date) %>%
  arrange(date) %>%
  summarize(
    country = "World", iso3c = NA, confirmed = sum(confirmed),
    deaths = sum(deaths), recovered = sum(recovered),
    timestamp = fmode(timestamp)
  ) %>%
  mutate(
    daily_confirmed = confirmed - lag(confirmed, n = 1),
    daily_deaths = deaths - lag(deaths, n = 1),
    daily_recovered = recovered - lag(recovered, n = 1)
  ) %>%
  mutate(
    daily_confirmed = replace_na(daily_confirmed, 0),
    daily_deaths = replace_na(daily_deaths, 0),
    daily_recovered = replace_na(daily_recovered, 0)
  ) %>%
  ungroup() %>%
  arrange(country, iso3c, date)

add_world2 <- merged %>%
  group_by(country, iso3c) %>%
  summarize(
    population = fmode(population),
    land_area_skm = fmode(land_area_skm),
    timestamp = fmode(timestamp)
  ) %>%
  ungroup() %>%
  summarize(
    country = "World", iso3c = NA,
    population = sum(population, na.rm = TRUE),
    land_area_skm = sum(land_area_skm, na.rm = TRUE)
  ) %>%
  mutate(pop_density = population / land_area_skm)

add_world <- left_join(add_world1, add_world2, by = c("country", "iso3c"))
merged <- bind_rows(merged, add_world)

cv_data <- pivot_longer(merged,
  cols = c(
    "confirmed", "deaths", "recovered",
    "daily_confirmed", "daily_deaths", "daily_recovered"
  ),
  names_to = "variable", values_to = "cases"
) %>%
  arrange(country, variable, date) %>%
  rename(area = land_area_skm, density = pop_density) %>%
  mutate(rate = cases / population * 10^6)


##Function 
cv_summary <- function(d, country_list = "World",
                       plot = TRUE, facet = "country",
                       status = c("confirmed", "deaths", "recovered")) {

  # based on `wes_palettes()` GrandBudapest1, IsleofDogs1, IsleofDogs2
  # from the {wesanderson} package
  my_palette <- c(
    "#5B1A18", "#FD6467", "#F1BB7B", "#D67236",
    "#0F0D0E", "#9986A5", "#79402E", "#CCBA72", "#D9D0D3", "#8D8680",
    "#EAD3BF", "#AA9486", "#B6854D", "#39312F", "#1C1718"
  )

  if (facet == "country") {
    fill <- "variable"
    n <- length(unique(d$variable)) / 2
    # need only half of unique # of variable (3)
  }

  if (facet == "variable") {
    fill <- "country"
    n <- length(country_list)
    # need number of countries
  }

  if ("All" %in% country_list) {
    country_list <- unique(d$country)
    country_list <- setdiff(country_list, "World")
  }

  if ("World" %in% country_list) {
    d <- d %>% filter(country %in% country_list)

    totals <- d %>%
      group_by(variable) %>%
      summarize(
        country = "World",
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date)
      ) %>%
      select(country, variable, cases, population, area, density, rate, on) %>%
      arrange(variable) %>%
      ungroup()
  }

  if ("World" %nin% country_list) {
    d <- d %>% filter(country %in% country_list)
    totals <- d %>%
      group_by(country, variable) %>%
      summarize(
        cases = max(cases),
        population = max(population),
        area = max(area),
        density = max(density),
        rate = max(rate, na.rm = TRUE),
        on = max(date),
        gdp_capita = fmode(gdp_capita),
        income = fmode(income),
        life_expectancy = fmode(life_expectancy),
        max_sd = max(soc_dist),
        max_mr = max(mov_rest)
      ) %>%
      select(
        country, variable, cases, population, area, density, rate,
        gdp_capita, income, life_expectancy, max_sd, max_mr, on
      ) %>%
      arrange(country, variable) %>%
      ungroup()
  }

  if (plot == TRUE) {
    cc <- filter(d, variable %in% status)
    cum_cases_plot <- ggplot(
      data = cc,
      # use the tidy evaluation pronoun .data to slice the chosen fill
      # variable from the data frame
      aes(
        x = date, y = cases + 1, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      # use the tidy evaluation pronoun .data to slice the chosen facet_wrap
      # variable from the data frame
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Log Cumulative Cases") +
      scale_y_log10(
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))
      ) +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )

    dc <- filter(d, variable %in% paste0("daily_", status))
    daily_cases_plot <- ggplot(
      data = dc,
      aes(
        x = date, y = cases, color = .data[[fill]],
        fill = .data[[fill]]
      )
    ) +
      geom_point(size = 0.5) +
      geom_line() +
      facet_wrap(~ .data[[facet]], ncol = 5) +
      xlab("Date") +
      ylab("Daily Cases") +
      scale_color_manual(
        aesthetics = c("color", "fill"),
        name = NULL, values = my_palette
      )
  }

  if (plot == TRUE) {
    return(list(
      totals = totals,
      cum_cases_plot = cum_cases_plot,
      daily_cases_plot = daily_cases_plot
    ))
  } else {
    return(list(totals = totals))
  }
}

```


## Challenge 1

```{r}
#using function to graph data
cv_summary(d = cv_data)
```


## Challenge 2

```{r}
# Plotting G7 plus China Russia and Iran 
cv_summary(d = cv_data, country_list=c("US","United Kingdom","Canada","France","Germany","Italy","Japan","China","Russia","Iran"),
           facet="country")

```

## Challenge 3

```{r}
#All countries 
d<-cv_summary(d=cv_data, country_list="All", plot="FALSE") 
d 

#Only including countries with population over 1 million 
d<-d[[1]] %>%
  filter(population>1000000)
d

#Finding number of unique countries, counting these
d_unique<-unique(d) %>%
  length()
d_unique
  
```

## Challenge 4

```{r}
#overall tibble
overall<-filter(d,variable == "confirmed")

#daily tibble
daily<-filter(d,variable == "daily_confirmed")

#countries with highest overall rate of cases
overall%>%
  arrange(desc(cases))%>%
  head(n=10)

#countries with highest daily rate of cases 
daily%>%
  arrange(desc(cases))%>%
  head(n=10)

```

## Challenge 5

```{r}
#rate vs density------------------------------------------------
lm(rate ~ density,data=overall) %>%
summary()

g<-ggplot(data=overall,aes(x=density, y=rate))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

#log transformation
g<-ggplot(data=overall,aes(x=log(density), y=log(rate)))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

#adjusted model
lm(log(rate) ~ log(density),data=overall) %>%
summary()

#rate vs population------------------------------------------------
lm(rate ~ population,data=overall)%>%
  summary()

g<-ggplot(data=overall,aes(x=population, y=rate))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

#log transformation
g<-ggplot(data=overall,aes(x=log(population), y=log(rate)))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

lm(log(rate) ~ log(population),data=overall)%>%
  summary()

#rate vs gdp_capita------------------------------------------------
lm(rate ~ gdp_capita,data=overall)%>%
  summary()

g<-ggplot(data=overall,aes(x=gdp_capita, y=rate))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

#log transformation
g<-ggplot(data=overall,aes(x=log(gdp_capita), y=log(rate)))+ 
  geom_point() + 
  geom_smooth(method="lm")
g

lm(log(rate) ~ log(gdp_capita),data=overall)%>%
  summary()

#rate vs income------------------------------------------------
lm(rate ~ income,data=overall)%>%
  summary()

#Changing order of "income levels"
overall$income <- factor(overall$income,
    levels = c('Low income','Lower middle income','Upper middle income','High income'),ordered = TRUE)

#original plot 
g<-ggplot(data=overall,aes(x=income, y=rate))+ 
  geom_boxplot()
g

#log transformation
g<-ggplot(data=overall,aes(x=income, y=log(rate)))+ 
  geom_boxplot()
g

lm(log(rate) ~ income,data=overall)%>%
  summary()

```

## Challenge 6

```{r}

```

## Challenge 7

```{r}

```

## Challenge 8

```{r}

```